line-length = 120
exclude = [".venv", "alembic"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"


[lint.isort]
case-sensitive = true
combine-as-imports = true
detect-same-package = false

[lint]
# Enable D400 on top of the Google convention.
extend-select = ["D400"]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "N", # PEP8 naming convetions
    "FAST", # FastAPI conventions
    #    "D"  # pydocstyle
]
ignore = [
    "C901", # too complex
    "W191", # indentation contains tabs
    "D401", # imperative mood
    "D417", # documentation for every function parameter
    "D202",
    "D415",
    "D403",
    "D100"
]
fixable = ["ALL"]
unfixable = []

[lint.pycodestyle]
ignore-overlong-task-comments = true

[lint.pydocstyle]
convention = "google"
